name: pizzaria_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.18.4
  flutter_localizations: 
    sdk: flutter
  intl: ^0.19.0  # Atualizei para a versão correta
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mask_text_input_formatter: ^2.0.2

flutter:
  uses-material-design: true

  assets: 
    - assets/img/logo.jpg
    - assets/img/pizza_cogumelos.jpg
    - assets/img/pizza_marguerita.jpg
    - assets/img/pizza_cogumelos_grande.jpg